// examples/nextjs/app/page.tsx
'use client'

import { useState, useEffect } from 'react'

export default function Home() {
  const [health, setHealth] = useState<{ status: string; framework: string } | null>(null)
  const [greeting, setGreeting] = useState<string>('')
  const [name, setName] = useState('World')

  useEffect(() => {
    fetch('/api/rpc/health', { method: 'POST' })
      .then((r) => r.json())
      .then(setHealth)
  }, [])

  const greet = async () => {
    const res = await fetch('/api/rpc/greet', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name }),
    })
    const data = await res.json()
    setGreeting(data.greeting)
  }

  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>Katman + Next.js</h1>
      <p>Health: {health ? `${health.status} (${health.framework})` : 'loading...'}</p>
      <div style={{ marginTop: '1rem' }}>
        <input value={name} onChange={(e) => setName(e.target.value)} placeholder='Enter your name' />
        <button onClick={greet} style={{ marginLeft: '0.5rem' }}>
          Greet
        </button>
      </div>
      {greeting && <p style={{ marginTop: '1rem' }}>{greeting}</p>}
    </main>
  )
}

// examples/nuxt/app.vue
<script setup lang="ts">
const health = ref<{ status: string; framework: string } | null>(null)
const greeting = ref('')
const name = ref('World')


onMounted(async () => {
  const data = await $fetch('/rpc/health', { method: 'POST' })
  health.value = data as { status: string; framework: string }
})


async function greet() {
  const data = await $fetch('/rpc/greet', {
    method: 'POST',
    body: { name: name.value },
  })
  greeting.value = (data as { greeting: string }).greeting
}
</script>

<template>
  <main style="padding: 2rem; font-family: system-ui">
    <h1>Katman + Nuxt</h1>
    <p>Health: {{ health ? `${health.status} (${health.framework})` : 'loading...' }}</p>
    <div style="margin-top: 1rem">
      <input v-model="name" placeholder="Enter your name" />
      <button style="margin-left: 0.5rem" @click="greet">Greet</button>
    </div>
    <p v-if="greeting" style="margin-top: 1rem">{{ greeting }}</p>
  </main>
</template>
